// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audits.sql

package store

import (
	"context"
	"database/sql"
	"time"
)

const createAudit = `-- name: CreateAudit :exec
INSERT INTO audits (
    id, plan_id, plan_name, checklist_id, checklist_name,
    started_at, duration_ms, total_endpoints, passed_count,
    failed_count, skipped_count, highest_severity
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAuditParams struct {
	ID              string         `json:"id"`
	PlanID          sql.NullString `json:"plan_id"`
	PlanName        string         `json:"plan_name"`
	ChecklistID     sql.NullString `json:"checklist_id"`
	ChecklistName   string         `json:"checklist_name"`
	StartedAt       time.Time      `json:"started_at"`
	DurationMs      int64          `json:"duration_ms"`
	TotalEndpoints  int64          `json:"total_endpoints"`
	PassedCount     int64          `json:"passed_count"`
	FailedCount     int64          `json:"failed_count"`
	SkippedCount    int64          `json:"skipped_count"`
	HighestSeverity string         `json:"highest_severity"`
}

func (q *Queries) CreateAudit(ctx context.Context, arg CreateAuditParams) error {
	_, err := q.db.ExecContext(ctx, createAudit,
		arg.ID,
		arg.PlanID,
		arg.PlanName,
		arg.ChecklistID,
		arg.ChecklistName,
		arg.StartedAt,
		arg.DurationMs,
		arg.TotalEndpoints,
		arg.PassedCount,
		arg.FailedCount,
		arg.SkippedCount,
		arg.HighestSeverity,
	)
	return err
}

const deleteAudit = `-- name: DeleteAudit :exec
DELETE FROM audits
WHERE id = ?
`

func (q *Queries) DeleteAudit(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAudit, id)
	return err
}

const getAudit = `-- name: GetAudit :one
SELECT id, plan_id, plan_name, checklist_id, checklist_name, started_at, duration_ms, total_endpoints, passed_count, failed_count, skipped_count, highest_severity FROM audits
WHERE id = ? LIMIT 1
`

func (q *Queries) GetAudit(ctx context.Context, id string) (Audit, error) {
	row := q.db.QueryRowContext(ctx, getAudit, id)
	var i Audit
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.PlanName,
		&i.ChecklistID,
		&i.ChecklistName,
		&i.StartedAt,
		&i.DurationMs,
		&i.TotalEndpoints,
		&i.PassedCount,
		&i.FailedCount,
		&i.SkippedCount,
		&i.HighestSeverity,
	)
	return i, err
}

const listAudits = `-- name: ListAudits :many
SELECT id, plan_id, plan_name, checklist_id, checklist_name, started_at, duration_ms, total_endpoints, passed_count, failed_count, skipped_count, highest_severity FROM audits
WHERE 
    (?3 IS NULL OR plan_id = ?3)
    AND
    (?4 IS NULL OR highest_severity = ?4)
ORDER BY started_at DESC
LIMIT ? OFFSET ?
`

type ListAuditsParams struct {
	PlanID          interface{} `json:"plan_id"`
	HighestSeverity interface{} `json:"highest_severity"`
	Limit           int64       `json:"limit"`
	Offset          int64       `json:"offset"`
}

func (q *Queries) ListAudits(ctx context.Context, arg ListAuditsParams) ([]Audit, error) {
	rows, err := q.db.QueryContext(ctx, listAudits,
		arg.PlanID,
		arg.HighestSeverity,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Audit
	for rows.Next() {
		var i Audit
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.PlanName,
			&i.ChecklistID,
			&i.ChecklistName,
			&i.StartedAt,
			&i.DurationMs,
			&i.TotalEndpoints,
			&i.PassedCount,
			&i.FailedCount,
			&i.SkippedCount,
			&i.HighestSeverity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
