// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checklists.sql

package store

import (
	"context"
	"time"
)

const createChecklist = `-- name: CreateChecklist :exec
INSERT INTO checklists (id, name, description, check_names, is_active, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateChecklistParams struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	CheckNames  string    `json:"check_names"`
	IsActive    bool      `json:"is_active"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) CreateChecklist(ctx context.Context, arg CreateChecklistParams) error {
	_, err := q.db.ExecContext(ctx, createChecklist,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.CheckNames,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deactivateAllChecklists = `-- name: DeactivateAllChecklists :exec
UPDATE checklists
SET is_active = 0
`

func (q *Queries) DeactivateAllChecklists(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deactivateAllChecklists)
	return err
}

const deleteChecklist = `-- name: DeleteChecklist :exec
DELETE FROM checklists
WHERE id = ?
`

func (q *Queries) DeleteChecklist(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteChecklist, id)
	return err
}

const getActiveChecklist = `-- name: GetActiveChecklist :one
SELECT id, name, description, check_names, is_active, created_at, updated_at FROM checklists
WHERE is_active = 1
LIMIT 1
`

func (q *Queries) GetActiveChecklist(ctx context.Context) (Checklist, error) {
	row := q.db.QueryRowContext(ctx, getActiveChecklist)
	var i Checklist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CheckNames,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChecklist = `-- name: GetChecklist :one
SELECT id, name, description, check_names, is_active, created_at, updated_at FROM checklists
WHERE id = ? LIMIT 1
`

func (q *Queries) GetChecklist(ctx context.Context, id string) (Checklist, error) {
	row := q.db.QueryRowContext(ctx, getChecklist, id)
	var i Checklist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CheckNames,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChecklists = `-- name: ListChecklists :many
SELECT id, name, description, check_names, is_active, created_at, updated_at FROM checklists
ORDER BY created_at DESC
`

func (q *Queries) ListChecklists(ctx context.Context) ([]Checklist, error) {
	rows, err := q.db.QueryContext(ctx, listChecklists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Checklist
	for rows.Next() {
		var i Checklist
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CheckNames,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setActiveChecklist = `-- name: SetActiveChecklist :exec
UPDATE checklists
SET is_active = 1, updated_at = ?
WHERE id = ?
`

type SetActiveChecklistParams struct {
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

func (q *Queries) SetActiveChecklist(ctx context.Context, arg SetActiveChecklistParams) error {
	_, err := q.db.ExecContext(ctx, setActiveChecklist, arg.UpdatedAt, arg.ID)
	return err
}

const updateChecklist = `-- name: UpdateChecklist :exec
UPDATE checklists
SET name = ?, description = ?, check_names = ?, updated_at = ?
WHERE id = ?
`

type UpdateChecklistParams struct {
	Name        string    `json:"name"`
	Description string    `json:"description"`
	CheckNames  string    `json:"check_names"`
	UpdatedAt   time.Time `json:"updated_at"`
	ID          string    `json:"id"`
}

func (q *Queries) UpdateChecklist(ctx context.Context, arg UpdateChecklistParams) error {
	_, err := q.db.ExecContext(ctx, updateChecklist,
		arg.Name,
		arg.Description,
		arg.CheckNames,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
