// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql"
	"time"
)

type Audit struct {
	ID              string         `json:"id"`
	PlanID          sql.NullString `json:"plan_id"`
	PlanName        string         `json:"plan_name"`
	ChecklistID     sql.NullString `json:"checklist_id"`
	ChecklistName   string         `json:"checklist_name"`
	StartedAt       time.Time      `json:"started_at"`
	DurationMs      int64          `json:"duration_ms"`
	TotalEndpoints  int64          `json:"total_endpoints"`
	PassedCount     int64          `json:"passed_count"`
	FailedCount     int64          `json:"failed_count"`
	SkippedCount    int64          `json:"skipped_count"`
	HighestSeverity string         `json:"highest_severity"`
}

type Checklist struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	CheckNames  string    `json:"check_names"`
	IsActive    bool      `json:"is_active"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Plan struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Urls      string    `json:"urls"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Report struct {
	ID              string `json:"id"`
	AuditID         string `json:"audit_id"`
	Url             string `json:"url"`
	FinalUrl        string `json:"final_url"`
	StatusCode      int64  `json:"status_code"`
	DurationMs      int64  `json:"duration_ms"`
	PassedCount     int64  `json:"passed_count"`
	FailedCount     int64  `json:"failed_count"`
	SkippedCount    int64  `json:"skipped_count"`
	HighestSeverity string `json:"highest_severity"`
	Issues          string `json:"issues"`
}
