// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plans.sql

package store

import (
	"context"
	"time"
)

const createPlan = `-- name: CreatePlan :exec
INSERT INTO plans (id, name, urls, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
`

type CreatePlanParams struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Urls      string    `json:"urls"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) error {
	_, err := q.db.ExecContext(ctx, createPlan,
		arg.ID,
		arg.Name,
		arg.Urls,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deletePlan = `-- name: DeletePlan :exec
DELETE FROM plans
WHERE id = ?
`

func (q *Queries) DeletePlan(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePlan, id)
	return err
}

const getPlan = `-- name: GetPlan :one
SELECT id, name, urls, created_at, updated_at FROM plans
WHERE id = ? LIMIT 1
`

func (q *Queries) GetPlan(ctx context.Context, id string) (Plan, error) {
	row := q.db.QueryRowContext(ctx, getPlan, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Urls,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPlans = `-- name: ListPlans :many
SELECT id, name, urls, created_at, updated_at FROM plans
ORDER BY created_at DESC
`

func (q *Queries) ListPlans(ctx context.Context) ([]Plan, error) {
	rows, err := q.db.QueryContext(ctx, listPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plan
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Urls,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlan = `-- name: UpdatePlan :exec
UPDATE plans
SET name = ?, urls = ?, updated_at = ?
WHERE id = ?
`

type UpdatePlanParams struct {
	Name      string    `json:"name"`
	Urls      string    `json:"urls"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

func (q *Queries) UpdatePlan(ctx context.Context, arg UpdatePlanParams) error {
	_, err := q.db.ExecContext(ctx, updatePlan,
		arg.Name,
		arg.Urls,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
