// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	CreateAudit(ctx context.Context, arg CreateAuditParams) error
	CreateChecklist(ctx context.Context, arg CreateChecklistParams) error
	CreatePlan(ctx context.Context, arg CreatePlanParams) error
	CreateReport(ctx context.Context, arg CreateReportParams) error
	DeactivateAllChecklists(ctx context.Context) error
	DeleteAudit(ctx context.Context, id string) error
	DeleteChecklist(ctx context.Context, id string) error
	DeletePlan(ctx context.Context, id string) error
	GetActiveChecklist(ctx context.Context) (Checklist, error)
	GetAudit(ctx context.Context, id string) (Audit, error)
	GetChecklist(ctx context.Context, id string) (Checklist, error)
	GetPlan(ctx context.Context, id string) (Plan, error)
	ListAudits(ctx context.Context, arg ListAuditsParams) ([]Audit, error)
	ListChecklists(ctx context.Context) ([]Checklist, error)
	ListPlans(ctx context.Context) ([]Plan, error)
	ListReportsByAuditID(ctx context.Context, auditID string) ([]Report, error)
	SetActiveChecklist(ctx context.Context, arg SetActiveChecklistParams) error
	UpdateChecklist(ctx context.Context, arg UpdateChecklistParams) error
	UpdatePlan(ctx context.Context, arg UpdatePlanParams) error
}

var _ Querier = (*Queries)(nil)
