// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package store

import (
	"context"
)

const createReport = `-- name: CreateReport :exec
INSERT INTO reports (
    id, audit_id, url, final_url, status_code,
    duration_ms, passed_count, failed_count,
    skipped_count, highest_severity, issues
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateReportParams struct {
	ID              string `json:"id"`
	AuditID         string `json:"audit_id"`
	Url             string `json:"url"`
	FinalUrl        string `json:"final_url"`
	StatusCode      int64  `json:"status_code"`
	DurationMs      int64  `json:"duration_ms"`
	PassedCount     int64  `json:"passed_count"`
	FailedCount     int64  `json:"failed_count"`
	SkippedCount    int64  `json:"skipped_count"`
	HighestSeverity string `json:"highest_severity"`
	Issues          string `json:"issues"`
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) error {
	_, err := q.db.ExecContext(ctx, createReport,
		arg.ID,
		arg.AuditID,
		arg.Url,
		arg.FinalUrl,
		arg.StatusCode,
		arg.DurationMs,
		arg.PassedCount,
		arg.FailedCount,
		arg.SkippedCount,
		arg.HighestSeverity,
		arg.Issues,
	)
	return err
}

const listReportsByAuditID = `-- name: ListReportsByAuditID :many
SELECT id, audit_id, url, final_url, status_code, duration_ms, passed_count, failed_count, skipped_count, highest_severity, issues FROM reports
WHERE audit_id = ?
ORDER BY id ASC
`

func (q *Queries) ListReportsByAuditID(ctx context.Context, auditID string) ([]Report, error) {
	rows, err := q.db.QueryContext(ctx, listReportsByAuditID, auditID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Report
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.AuditID,
			&i.Url,
			&i.FinalUrl,
			&i.StatusCode,
			&i.DurationMs,
			&i.PassedCount,
			&i.FailedCount,
			&i.SkippedCount,
			&i.HighestSeverity,
			&i.Issues,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
